# Generated by Django 2.2.3 on 2020-02-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('contractorName', models.CharField(blank=True, max_length=127, null=True)),
                ('client', models.CharField(blank=True, max_length=127, null=True)),
                ('finalAmount', models.CharField(blank=True, max_length=127, null=True)),
                ('cStartDate', models.DateField(blank=True, null=True)),
                ('bossName', models.CharField(blank=True, max_length=255, null=True)),
                ('nonCashAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('cashAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('terminationContractDetail', models.CharField(blank=True, max_length=255, null=True)),
                ('additionDetail', models.CharField(blank=True, max_length=255, null=True)),
                ('cDuration', models.CharField(blank=True, max_length=255, null=True)),
                ('cSelect', models.CharField(blank=True, max_length=255, null=True)),
                ('cNationalId', models.CharField(blank=True, max_length=255, null=True)),
                ('cEconomicId', models.CharField(blank=True, max_length=255, null=True)),
                ('cId', models.CharField(blank=True, max_length=255, null=True)),
                ('cBirthday', models.CharField(blank=True, max_length=255, null=True)),
                ('reasonLeave', models.CharField(blank=True, max_length=255, null=True)),
                ('hasTax', models.BooleanField()),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('moderator', models.CharField(blank=True, max_length=255, null=True)),
                ('winMethod', models.CharField(blank=True, max_length=255, null=True)),
                ('memberCommision', models.TextField(blank=True, null=True)),
                ('signClient', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('beneficiary', models.CharField(max_length=127)),
                ('client', models.CharField(max_length=127)),
                ('finalAmount', models.CharField(max_length=127)),
                ('cStartDate', models.DateField()),
                ('bossName', models.CharField(max_length=255)),
                ('terminationContractDetail', models.CharField(blank=True, max_length=255, null=True)),
                ('additionDetail', models.CharField(blank=True, max_length=255, null=True)),
                ('cDuration', models.CharField(max_length=255)),
                ('cSelectMethod', models.CharField(max_length=255)),
                ('kNationalId', models.CharField(max_length=255)),
                ('kEconomicId', models.CharField(max_length=255)),
                ('kId', models.CharField(blank=True, max_length=255, null=True)),
                ('kBirthday', models.CharField(blank=True, max_length=255, null=True)),
                ('hasTax', models.BooleanField()),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('moderator', models.CharField(max_length=255)),
                ('winMethod', models.CharField(blank=True, max_length=255, null=True)),
                ('memberCommision', models.TextField()),
                ('signClient', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Participatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('nameInvestor', models.CharField(max_length=127)),
                ('beneficiary', models.CharField(max_length=127)),
                ('cOveral', models.CharField(blank=True, max_length=127, null=True)),
                ('cStartDate', models.DateField()),
                ('projectName', models.CharField(blank=True, max_length=127, null=True)),
                ('useri', models.CharField(blank=True, max_length=127, null=True)),
                ('brMucipallity', models.CharField(blank=True, max_length=127, null=True)),
                ('INationalId', models.CharField(max_length=255)),
                ('IEconomicId', models.CharField(max_length=255)),
                ('IId', models.CharField(blank=True, max_length=255, null=True)),
                ('brInverstor', models.CharField(blank=True, max_length=127, null=True)),
                ('estimateOperationTime', models.CharField(blank=True, max_length=127, null=True)),
                ('partenrshipModel', models.CharField(blank=True, max_length=127, null=True)),
                ('projectAddress', models.TextField(blank=True, max_length=127, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('signClient', models.CharField(max_length=255)),
                ('bossName', models.CharField(max_length=255)),
                ('cModerator', models.CharField(max_length=255)),
                ('trustee', models.TextField(blank=True, max_length=127, null=True)),
            ],
        ),
    ]
